version: '3.8'

services:
  mi-sitio-php:
    build: .
    container_name: web_aneca
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - base-de-datos

  base-de-datos:
    image: mariadb:10.11
    container_name: bd_aneca
    restart: always
    environment:
      # Como vamos a crear múltiples bases de datos en el init.sql, 
      # aquí solo necesitamos definir la contraseña maestra (root).
      MYSQL_ROOT_PASSWORD: root_super_segura
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - datos_bd:/var/lib/mysql

volumes:
  datos_bd:
